'use strict';

// Declare app level module
// - 'templates' module is dynamically generated by the grunt-angular-templates task
angular.module('app', [
  'templates'
]);

angular.module('app').config(['$routeProvider', '$locationProvider', function ($routeProvider, $locationProvider) {
    
    $routeProvider.otherwise({redirectTo: '/'});

    // enable the HTML5 push/pop history API  
    $locationProvider.html5Mode(true);
  }]);