'use strict';

// Declare app level module
// - 'templates' module is dynamically generated by the grunt-angular-templates task
angular.module('app', [
  'templates',
  'home',
  'd3'
]);

angular.module('app')
  .config(function ($locationProvider, $urlRouterProvider) {
    
    $urlRouterProvider.otherwise('/');

    // enable the HTML5 push/pop history API  
    $locationProvider.html5Mode(true);
  });